import { CHAPTER_LENGTH } from '@/constants'
import { currentChapterAtom, currentDictInfoAtom, reviewModeInfoAtom } from '@/store'
import type { Word, WordWithIndex } from '@/typings/index'
import { wordListFetcher } from '@/utils/wordListFetcher'
import { useAtom, useAtomValue } from 'jotai'
import { useMemo } from 'react'
import useSWR from 'swr'

// English definitions for common words
const englishDefinitions: Record<string, string[]> = {
  // Elementary Grade 1-2 Vocabulary
  book: ['a written or printed work with pages'],
  ruler: ['a straight measuring tool'],
  pencil: ['a writing tool with graphite'],
  schoolbag: ['a bag for carrying school items'],
  teacher: ['a person who teaches students'],
  I: ['the person speaking'],
  have: ['to possess or own'],
  a: ['one, used before singular nouns'],
  an: ['one, used before singular nouns starting with vowel'],
  face: ['the front part of the head'],
  ear: ['the organ for hearing'],
  eye: ['the organ for seeing'],
  nose: ['the organ for smelling'],
  mouth: ['the opening for eating and speaking'],
  this: ['referring to something nearby'],
  is: ['present tense of be'],
  my: ['belonging to me'],
  dog: ['a common pet animal'],
  bird: ['a flying animal with feathers'],
  tiger: ['a large striped cat'],
  monkey: ['a tree-climbing animal'],
  cat: ['a small furry pet'],
  what: ['asking for information'],
  it: ['referring to a thing'],
  one: ['the number 1'],
  two: ['the number 2'],
  three: ['the number 3'],
  four: ['the number 4'],
  five: ['the number 5'],
  six: ['the number 6'],
  seven: ['the number 7'],
  eight: ['the number 8'],
  nine: ['the number 9'],
  ten: ['the number 10'],
  red: ['the color of blood'],
  blue: ['the color of sky'],
  green: ['the color of grass'],
  yellow: ['the color of sun'],
  black: ['the color of night'],
  white: ['the color of snow'],
  big: ['large in size'],
  small: ['little in size'],
  good: ['nice, pleasant'],
  bad: ['not good, poor'],
  happy: ['feeling joy'],
  sad: ['feeling sorrow'],
  hot: ['having high temperature'],
  cold: ['having low temperature'],
  new: ['not old, recent'],
  old: ['not old, aged'],
  young: ['not old, youthful'],
  tall: ['high in height'],
  short: ['low in height'],
  long: ['extending far'],
  fast: ['moving quickly'],
  slow: ['moving slowly'],
  up: ['toward higher position'],
  down: ['toward lower position'],
  in: ['inside, within'],
  out: ['outside, not in'],
  on: ['touching the surface'],
  under: ['below, beneath'],
  over: ['above, across'],
  here: ['at this place'],
  there: ['at that place'],
  yes: ['affirmative answer'],
  no: ['negative answer'],
  please: ['polite request word'],
  thank: ['to express gratitude'],
  you: ['the person being spoken to'],
  he: ['male person'],
  she: ['female person'],
  we: ['I and others'],
  they: ['those people'],
  am: ['present tense of be (I)'],
  are: ['present tense of be (you/we/they)'],
  was: ['past tense of be'],
  were: ['past tense of be (plural)'],
  be: ['to exist, to be'],
  do: ['to perform an action'],
  does: ['present tense of do (he/she/it)'],
  did: ['past tense of do'],
  can: ['to be able to'],
  will: ['future tense helper'],
  would: ['conditional helper'],
  should: ['ought to'],
  could: ['past tense of can'],
  may: ['might, permission'],
  might: ['possibility'],
  must: ['have to, required'],
  shall: ['future tense helper'],
  go: ['to move from place'],
  come: ['to move toward place'],
  get: ['to obtain, receive'],
  give: ['to hand over'],
  take: ['to grab, carry'],
  make: ['to create, produce'],
  see: ['to look at'],
  look: ['to direct eyes'],
  hear: ['to perceive sound'],
  listen: ['to pay attention to sound'],
  speak: ['to talk'],
  talk: ['to have conversation'],
  say: ['to express in words'],
  tell: ['to inform, narrate'],
  ask: ['to request information'],
  answer: ['to respond to question'],
  know: ['to have information'],
  think: ['to use mind'],
  feel: ['to experience emotion'],
  want: ['to desire'],
  need: ['to require'],
  like: ['to enjoy'],
  love: ['to have strong affection'],
  hate: ['to strongly dislike'],
  help: ['to assist'],
  play: ['to have fun'],
  work: ['to do job'],
  study: ['to learn'],
  learn: ['to gain knowledge'],
  teach: ['to give instruction'],
  read: ['to look at words'],
  write: ['to form letters'],
  draw: ['to make picture'],
  sing: ['to make music with voice'],
  dance: ['to move to music'],
  run: ['to move fast on feet'],
  walk: ['to move on feet'],
  jump: ['to leap up'],
  sit: ['to rest on bottom'],
  stand: ['to be on feet'],
  sleep: ['to rest with eyes closed'],
  eat: ['to consume food'],
  drink: ['to consume liquid'],
  cook: ['to prepare food'],
  wash: ['to clean with water'],
  clean: ['to make tidy'],
  dirty: ['not clean'],
  open: ['not closed'],
  close: ['to shut'],
  start: ['to begin'],
  stop: ['to end'],
  finish: ['to complete'],
  begin: ['to start'],
  end: ['to finish'],
  first: ['coming before others'],
  last: ['coming after others'],
  next: ['following in order'],
  before: ['earlier than'],
  after: ['later than'],
  now: ['at this time'],
  then: ['at that time'],
  today: ['this day'],
  tomorrow: ['the day after today'],
  yesterday: ['the day before today'],
  morning: ['early part of day'],
  afternoon: ['middle part of day'],
  evening: ['late part of day'],
  night: ['dark part of day'],
  day: ['24-hour period'],
  week: ['7-day period'],
  month: ['30-day period'],
  year: ['12-month period'],
  time: ['measurement of duration'],
  hour: ['60-minute period'],
  minute: ['60-second period'],
  second: ['basic time unit'],
  home: ['place where you live'],
  house: ['building to live in'],
  room: ['space in building'],
  door: ['entrance barrier'],
  window: ['glass opening in wall'],
  table: ['flat surface for things'],
  chair: ['seat with back'],
  bed: ['furniture for sleeping'],
  desk: ['table for work'],
  floor: ['bottom surface of room'],
  wall: ['vertical surface of room'],
  ceiling: ['top surface of room'],
  kitchen: ['room for cooking'],
  bathroom: ['room for washing'],
  bedroom: ['room for sleeping'],
  living: ['room for relaxing'],
  family: ['related people living together'],
  mother: ['female parent'],
  father: ['male parent'],
  sister: ['female sibling'],
  brother: ['male sibling'],
  baby: ['very young child'],
  friend: ['person you like'],
  neighbor: ['person living nearby'],
  doctor: ['medical professional'],
  nurse: ['medical helper'],
  police: ['law enforcement officer'],
  firefighter: ['person who fights fires'],
  driver: ['person who drives'],
  farmer: ['person who grows food'],
  student: ['person who learns'],
  school: ['place for learning'],
  classroom: ['room for teaching'],
  library: ['place with books'],
  hospital: ['place for medical care'],
  store: ['place to buy things'],
  restaurant: ['place to eat food'],
  park: ['place with trees and grass'],
  zoo: ['place with animals'],
  museum: ['place with old things'],
  church: ['place for worship'],
  bank: ['place for money'],
  post: ['place for mail'],
  office: ['place for work'],
  factory: ['place for making things'],
  farm: ['place for growing food'],
  garden: ['place for growing plants'],
  street: ['road in city'],
  road: ['path for vehicles'],
  bridge: ['structure over water'],
  building: ['large structure'],
  tower: ['tall building'],
  // Clothing and Common Items
  watch: ['a timepiece worn on the wrist'],
  coat: ['outer garment, jacket'],
  dress: ['a one-piece garment for women'],
  skirt: ['a garment worn from waist down'],
  shirt: ['a garment for the upper body'],
  pants: ['garment for legs'],
  shoes: ['footwear'],
  hat: ['head covering'],
  gloves: ['hand coverings'],
  socks: ['foot coverings'],
  underwear: ['clothing worn under other clothes'],
  jacket: ['outer garment'],
  sweater: ['knitted upper garment'],
  jeans: ['denim pants'],
  shorts: ['short pants'],
  boots: ['footwear covering ankle'],
  sandals: ['open footwear'],
  belt: ['strip worn around waist'],
  tie: ['neck accessory'],
  scarf: ['neck or head covering'],
  glasses: ['eyewear for vision'],
  sunglasses: ['eyewear for sun protection'],
  bag: ['container for carrying things'],
  purse: ['small bag for money'],
  wallet: ['small case for money'],
  phone: ['device for communication'],
  computer: ['electronic device for work'],
  television: ['device for watching shows'],
  radio: ['device for listening to music'],
  camera: ['device for taking pictures'],
  bicycle: ['two-wheeled vehicle'],
  motorcycle: ['two-wheeled motor vehicle'],
  bus: ['large vehicle for passengers'],
  train: ['vehicle on tracks'],
  plane: ['flying vehicle'],
  boat: ['water vehicle'],
  ship: ['large water vehicle'],
  truck: ['large vehicle for cargo'],
  taxi: ['vehicle for hire'],
  ambulance: ['emergency medical vehicle'],
  fire: ['emergency fire vehicle'],
  key: ['tool for opening locks'],
  lock: ['device for securing doors'],
  mirror: ['reflective surface'],
  lamp: ['device for light'],
  candle: ['wax stick for light'],
  clock: ['device showing time'],
  calendar: ['device showing dates'],
  magazine: ['periodical publication'],
  newspaper: ['daily publication'],
  paper: ['material for writing'],
  notebook: ['book for writing notes'],
  folder: ['container for papers'],
  envelope: ['container for letters'],
  stamp: ['postal payment'],
  letter: ['written message'],
  package: ['wrapped item'],
  box: ['container with sides'],
  bottle: ['container with narrow neck'],
  cup: ['drinking vessel'],
  glass: ['drinking vessel made of glass'],
  plate: ['flat dish for food'],
  bowl: ['deep dish for food'],
  spoon: ['eating utensil'],
  fork: ['eating utensil with prongs'],
  knife: ['cutting tool'],
  napkin: ['cloth for cleaning'],
  towel: ['cloth for drying'],
  soap: ['cleaning substance'],
  shampoo: ['hair cleaning product'],
  // Common English Words
  excuse: ['to pardon, forgive'],
  me: ['the person speaking (object)'],
  handbag: ['small bag carried by hand'],
  pardon: ['to excuse, forgive'],
  ticket: ['piece of paper for admission'],
  number: ['mathematical symbol'],
  sorry: ['expression of regret'],
  sir: ['polite form of address for man'],
  cloakroom: ['room for storing coats'],
  suit: ['matching jacket and pants'],
  daughter: ['female child'],
  french: ['relating to France'],
  german: ['relating to Germany'],
  nice: ['pleasant, good'],
  meet: ['to come together'],
  japanese: ['relating to Japan'],
  korean: ['relating to Korea'],
  chinese: ['relating to China'],
  model: ['example, copy'],
  swedish: ['relating to Sweden'],
  english: ['relating to England'],
  american: ['relating to America'],
  volvo: ['Swedish car brand'],
  peugeot: ['French car brand'],
  mercedes: ['German car brand'],
  toyota: ['Japanese car brand'],
  daewoo: ['Korean car brand'],
  mini: ['small car brand'],
  ford: ['American car brand'],
  fiat: ['Italian car brand'],
  bentley: ['British car brand'],
  citroen: ['French car brand'],
  welcome: ['greeting to visitors'],
  perhaps: ['maybe, possibly'],
  // Grade 1-6 Additional Vocabulary
  blackboard: ['dark surface for writing with chalk'],
  running: ['moving fast on feet'],
  basketball: ['sport with ball and hoop'],
  roller: ['wheel for skating'],
  skating: ['moving on wheels or ice'],
  jumping: ['leaping up'],
  rope: ['thick cord'],
  clever: ['smart, intelligent'],
  careless: ['not careful'],
  polite: ['having good manners'],
  palace: ['large royal building'],
  potala: ['famous palace in Tibet'],
  // More Grade 1-6 Words
  apple: ['red or green fruit'],
  banana: ['yellow curved fruit'],
  orange: ['orange citrus fruit'],
  grape: ['small round fruit'],
  strawberry: ['red berry fruit'],
  watermelon: ['large green fruit'],
  bread: ['baked food from flour'],
  cake: ['sweet baked dessert'],
  cookie: ['small sweet treat'],
  candy: ['sweet confection'],
  chocolate: ['sweet brown treat'],
  ice: ['frozen water'],
  cream: ['dairy dessert'],
  milk: ['white dairy drink'],
  water: ['clear liquid'],
  juice: ['fruit liquid'],
  soda: ['carbonated drink'],
  tea: ['hot leaf drink'],
  coffee: ['hot bean drink'],
  meat: ['animal food'],
  fish: ['water animal food'],
  chicken: ['bird meat'],
  beef: ['cow meat'],
  pork: ['pig meat'],
  egg: ['oval food from bird'],
  cheese: ['dairy food'],
  butter: ['dairy spread'],
  salt: ['white seasoning'],
  sugar: ['sweet seasoning'],
  pepper: ['spicy seasoning'],
  rice: ['grain food'],
  noodle: ['long pasta food'],
  soup: ['liquid food'],
  salad: ['mixed vegetables'],
  sandwich: ['bread with filling'],
  pizza: ['flat bread with toppings'],
  hamburger: ['meat in bun'],
  warm: ['comfortable temperature'],
  cool: ['slightly cold'],
  sunny: ['with sun shining'],
  cloudy: ['with clouds'],
  rainy: ['with rain falling'],
  snowy: ['with snow falling'],
  windy: ['with wind blowing'],
  stormy: ['with strong weather'],
  spring: ['season of growth'],
  summer: ['hot season'],
  fall: ['season of leaves falling'],
  winter: ['cold season'],
  weather: ['atmospheric conditions'],
  temperature: ['measure of heat'],
  rain: ['water falling from sky'],
  snow: ['frozen water falling'],
  wind: ['moving air'],
  sun: ['bright star in sky'],
  moon: ['satellite of Earth'],
  star: ['bright point in sky'],
  sky: ['space above Earth'],
  cloud: ['white mass in sky'],
  earth: ['planet we live on'],
  world: ['all of Earth'],
  country: ['nation, land'],
  city: ['large town'],
  town: ['small city'],
  village: ['very small town'],
  state: ['region of country'],
  capital: ['main city of country'],
  flag: ['symbol of country'],
  map: ['picture of land'],
  north: ['direction toward pole'],
  south: ['direction away from pole'],
  east: ['direction of sunrise'],
  west: ['direction of sunset'],
  left: ['opposite of right'],
  right: ['opposite of right'],
  front: ['forward direction'],
  back: ['behind direction'],
  side: ['edge, part'],
  middle: ['center, between edges'],
  top: ['highest part'],
  bottom: ['lowest part'],
  inside: ['within, interior'],
  outside: ['beyond, exterior'],
  near: ['close to'],
  far: ['distant from'],
  high: ['tall, elevated'],
  low: ['short, not high'],
  deep: ['extending far down'],
  shallow: ['not deep'],
  wide: ['broad, extensive'],
  narrow: ['not wide'],
  thick: ['having depth'],
  thin: ['not thick'],
  heavy: ['having weight'],
  light: ['not heavy'],
  strong: ['having power'],
  weak: ['not strong'],
  hard: ['difficult, solid'],
  easy: ['not difficult'],
  soft: ['not hard'],
  smooth: ['not rough'],
  rough: ['not smooth'],
  sharp: ['having edge'],
  dull: ['not sharp'],
  bright: ['having light'],
  dark: ['not bright'],
  loud: ['having sound'],
  quiet: ['not loud'],
  quick: ['fast, rapid'],
  rapid: ['very fast'],
  sudden: ['happening quickly'],
  gradual: ['happening slowly'],
  early: ['before expected time'],
  late: ['after expected time'],
  soon: ['in short time'],
  immediately: ['right now'],
  never: ['at no time'],
  sometimes: ['at certain times'],
  often: ['frequently'],
  usually: ['most of the time'],
  rarely: ['not often'],
  seldom: ['rarely'],
  once: ['one time'],
  twice: ['two times'],
  few: ['small number'],
  little: ['small amount'],
  some: ['certain amount'],
  any: ['one or more'],
  all: ['every one'],
  every: ['each one'],
  each: ['every individual'],
  either: ['one of two'],
  neither: ['not either'],
  other: ['different one'],
  same: ['identical'],
  different: ['not same'],
  similar: ['alike'],
  various: ['different kinds'],
  several: ['more than two'],
  enough: ['sufficient amount'],
  too: ['excessively'],
  very: ['extremely'],
  quite: ['rather'],
  rather: ['somewhat'],
  pretty: ['quite, rather'],
  so: ['to such degree'],
  such: ['of that kind'],
  how: ['in what way'],
  when: ['at what time'],
  where: ['at what place'],
  why: ['for what reason'],
  who: ['what person'],
  whom: ['what person (object)'],
  whose: ['belonging to whom'],
  which: ['what one'],
  that: ['referring to something'],
  these: ['these things'],
  those: ['those things'],
  // Additional Grade 1-6 Words from Cambridge JOIN IN
  'morning tea': ['early morning tea and light meal'],
  // Grade 2-6 Additional Words
  'play football': ['to play the sport of football'],
  'fly a kite': ['to make a kite fly in the air'],
  'ride a bike': ['to travel on a bicycle'],
  science: ['study of natural world'],
  'across from': ['on the opposite side of'],
  'next to': ['beside, adjacent to'],
  'too much': ['excessive amount'],
  'go to bed': ['to go to sleep'],
  // Additional Basic Words
  'a/an': ['one, used before singular nouns'],
}

export type UseWordListResult = {
  words: WordWithIndex[]
  isLoading: boolean
  error: Error | undefined
}

/**
 * Use word lists from the current selected dictionary.
 */
export function useWordList(): UseWordListResult {
  const currentDictInfo = useAtomValue(currentDictInfoAtom)
  const [currentChapter, setCurrentChapter] = useAtom(currentChapterAtom)
  const { isReviewMode, reviewRecord } = useAtomValue(reviewModeInfoAtom)

  // Reset current chapter to 0, when currentChapter is greater than chapterCount.
  if (currentDictInfo && currentChapter >= currentDictInfo.chapterCount) {
    setCurrentChapter(0)
  }

  const isFirstChapter = !isReviewMode && currentDictInfo?.id === 'pep-sl-yi1' && currentChapter === 0
  const { data: wordList, error, isLoading } = useSWR(currentDictInfo?.url, wordListFetcher)

  const words: WordWithIndex[] = useMemo(() => {
    let newWords: Word[]
    if (isFirstChapter) {
      newWords = firstChapter
    } else if (isReviewMode) {
      newWords = reviewRecord?.words ?? []
    } else if (wordList) {
      newWords = wordList.slice(currentChapter * CHAPTER_LENGTH, (currentChapter + 1) * CHAPTER_LENGTH)
    } else {
      newWords = []
    }

    // 记录原始 index, 并对 word.trans 做兜底处理
    return newWords.map((word, index) => {
      let trans: string[]

      // Use English definitions if available, otherwise use original translations
      if (englishDefinitions[word.name]) {
        trans = englishDefinitions[word.name]
      } else if (Array.isArray(word.trans)) {
        trans = word.trans.filter((item) => typeof item === 'string')
      } else if (word.trans === null || word.trans === undefined || typeof word.trans === 'object') {
        trans = []
      } else {
        trans = [String(word.trans)]
      }

      return {
        ...word,
        index,
        trans,
      }
    })
  }, [isFirstChapter, isReviewMode, wordList, reviewRecord?.words, currentChapter])

  return { words, isLoading, error }
}

const firstChapter = [
  { name: 'cancel', trans: ['to cancel, revoke; to delete'], usphone: "'kænsl", ukphone: "'kænsl" },
  {
    name: 'explosive',
    trans: ['explosive; highly controversial', 'explosive (noun)'],
    usphone: "ɪk'splosɪv; ɪk'splozɪv",
    ukphone: "ɪk'spləusɪv",
  },
  { name: 'numerous', trans: ['numerous, many'], usphone: "'numərəs", ukphone: "'njuːmərəs" },
  { name: 'govern', trans: ['to dominate, be superior', 'to rule, govern, control'], usphone: "'ɡʌvɚn", ukphone: "'gʌvn" },
  { name: 'analyse', trans: ['to analyze; to decompose; to interpret'], usphone: "'æn(ə)laɪz", ukphone: "'ænəlaɪz" },
  { name: 'discourage', trans: ['to discourage, dishearten; to prevent, dissuade'], usphone: "dɪs'kɝɪdʒ", ukphone: "dɪs'kʌrɪdʒ" },
  { name: 'resemble', trans: ['to be like, similar to'], usphone: "rɪ'zɛmbl", ukphone: "rɪ'zembl" },
  {
    name: 'remote',
    trans: ['distant; remote; estranged; detached; minimal; aloof, cold; remote control'],
    usphone: "rɪ'mot",
    ukphone: "rɪ'məut",
  },
  { name: 'salary', trans: ['salary, wages'], usphone: "'sæləri", ukphone: "'sæləri" },
  { name: 'pollution', trans: ['pollution, pollutants'], usphone: "pə'luʃən", ukphone: "pə'luːʃn" },
  { name: 'pretend', trans: ['to pretend, feign'], usphone: "prɪ'tɛnd", ukphone: "prɪ'tend" },
  { name: 'kettle', trans: ['kettle'], usphone: "'kɛtl", ukphone: "'ketl" },
  { name: 'wreck', trans: ['wreck; wreckage; broken person', 'to destroy'], usphone: 'rɛk', ukphone: 'rek' },
  { name: 'drunk', trans: ['drunk; intoxicated'], usphone: 'drʌŋk', ukphone: 'drʌŋk' },
  { name: 'calculate', trans: ['to calculate; to estimate; to plan'], usphone: "'kælkjulet", ukphone: "'kælkjuleɪt" },
  { name: 'persistent', trans: ['persistent, unyielding; continuous; recurring'], usphone: "pə'zɪstənt", ukphone: "pə'sɪstənt" },
  { name: 'sake', trans: ['sake, reason'], usphone: 'sek', ukphone: 'seɪk' },
  { name: 'conceal', trans: ['to hide, conceal, cover up'], usphone: "kən'sil", ukphone: "kən'siːl" },
  { name: 'audience', trans: ['audience, spectators, readers'], usphone: "'ɔdɪəns", ukphone: "'ɔːdiəns" },
  { name: 'meanwhile', trans: ['meanwhile, at the same time'], usphone: "'minwaɪl", ukphone: "'miːnwaɪl" },
]
